-- MySQL Script generated by MySQL Workbench
-- Sat Sep 10 11:07:22 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema default_schema
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema myTest
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `myTest` ;

-- -----------------------------------------------------
-- Schema myTest
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `myTest` DEFAULT CHARACTER SET utf8 ;
USE `myTest` ;

-- -----------------------------------------------------
-- Table `myTest`.`tbl_enterprises`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `myTest`.`tbl_enterprises` ;

CREATE TABLE IF NOT EXISTS `myTest`.`tbl_enterprises` (
  `id` INT NOT NULL,
  `created_by` VARCHAR(45) NOT NULL,
  `created_date` DATE NOT NULL,
  `modified_by` VARCHAR(45) NULL DEFAULT NULL,
  `modified_date` DATE NULL DEFAULT NULL,
  `status` TINYINT NULL DEFAULT NULL,
  `address` VARCHAR(45) NULL DEFAULT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `phone` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myTest`.`tbl_departments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `myTest`.`tbl_departments` ;

CREATE TABLE IF NOT EXISTS `myTest`.`tbl_departments` (
  `id` INT NOT NULL,
  `created_by` VARCHAR(45) NOT NULL,
  `created_date` DATE NOT NULL,
  `modified_by` VARCHAR(45) NULL DEFAULT NULL,
  `modified_date` DATE NULL DEFAULT NULL,
  `status` TINYINT NULL DEFAULT NULL,
  `description` VARCHAR(45) NULL DEFAULT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `phone` VARCHAR(45) NULL DEFAULT NULL,
  `id_enterprise` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tbl_departments_tbl_enterprises_idx` (`id_enterprise` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_departments_tbl_enterprises`
    FOREIGN KEY (`id_enterprise`)
    REFERENCES `myTest`.`tbl_enterprises` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myTest`.`tbl_employees`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `myTest`.`tbl_employees` ;

CREATE TABLE IF NOT EXISTS `myTest`.`tbl_employees` (
  `id` INT NOT NULL,
  `created_by` VARCHAR(45) NOT NULL,
  `created_date` DATE NOT NULL,
  `modified_by` VARCHAR(45) NULL DEFAULT NULL,
  `modified_date` DATE NULL DEFAULT NULL,
  `status` TINYINT NULL DEFAULT NULL,
  `age` INT NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `position` VARCHAR(45) NULL DEFAULT NULL,
  `surname` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myTest`.`tbl_departments_employees`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `myTest`.`tbl_departments_employees` ;

CREATE TABLE IF NOT EXISTS `myTest`.`tbl_departments_employees` (
  `id` INT NOT NULL,
  `created_by` VARCHAR(45) NOT NULL,
  `created_date` DATE NOT NULL,
  `modified_by` VARCHAR(45) NULL DEFAULT NULL,
  `modified_date` DATE NULL DEFAULT NULL,
  `status` TINYINT NULL DEFAULT NULL,
  `id_department` INT NOT NULL,
  `id_employees` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tbl_departments_employees_tbl_departments_idx` (`id_department` ASC) VISIBLE,
  INDEX `fk_tbl_departments_employees_tbl_employees1_idx` (`id_employees` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_departments_employees_tbl_departments`
    FOREIGN KEY (`id_department`)
    REFERENCES `myTest`.`tbl_departments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_departments_employees_tbl_employees1`
    FOREIGN KEY (`id_employees`)
    REFERENCES `myTest`.`tbl_employees` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
